import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/Footer"
import Navebar from "../components/Navebar"


export const metadata: Metadata = {
  title: "CHEFFINGTON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="">
        <Navebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
